### ISSUE TITLE
Bug: runslip.inversionGFs function takes 21 arguments (20 given) when run the nepal example

### ISSUE THREAD

**Issue by qingkaikong** [dmelgarm/MudPy#1]
I am trying to run the nepal earthquake example, when I compute GFs in nepal.inv.py, I got the error:

Traceback (most recent call last):
  File "nepal.inv.py", line 73, in <module>
    pmax,kmax,beta,time_epi,hot_start,ncpus)
TypeError: inversionGFs() takes exactly 21 arguments (20 given)

It seems the function inversionGFs()  has one more argument 'custom_stf' that is not in the nepal.inv.py calling.

**Comment by dmelgarm** [comment]
Fixed, I hadn't pushed in a while, this should not be an issue now.

**Comment by dequiroga** [comment]
I am trying to run the nepal earthquake example, when I compute nepal.fwd.py for forward modelling running the green functions and synthetics, I got the error:

Traceback (most recent call last):
  File "nepal.fwd.py", line 66, in <module>
    dt,NFFT,static,tsunami,hot_start,dk,pmin,pmax,kmax)
  File "/home/MudPy/src/python/mudpy/runslip.py", line 170, in make_green
    copy('staticgf',green_path+'static/'+model_name+'.static.'+strdepth+'.sub'+subfault)
  File "/usr/lib/python2.7/shutil.py", line 133, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'staticgf'

I have not found any information about this 'staticgf' on the example guide.
