### ISSUE TITLE
Can it do multi-segment finite fault model inversion?

### ISSUE THREAD

**Issue by tututingting** [dmelgarm/MudPy#25]
I have noticed that a lot of earthquakes have more than one-segment finite fault, I wonder whether the mudpy can do multi-segment finite fault model inversion?

**Comment by dmelgarm** [comment]
Yes. Put all your segments in one single .fault file and make sure the subfault numbers are concurrent i.e. if segment 1 has 100 faults and segment 2 has 50 subfaults then the subfault numbers in the .fault file should be continuos like 1,2,3, ... , 99,100,101, ... , 149, 150 and most importantly **you can't use laplacian smoothing** when you have a multi segment file, you can only use minimum-norm regularization so **set Ltype = 0**

**Comment by tututingting** [comment]
Thank you for your help.
