### ISSUE TITLE
reduce the dimension for GPS station

### ISSUE THREAD

**Issue by tututingting** [dmelgarm/MudPy#29]
Although there are more and more GPS stations, there are several GPS stations can be used for many earthquakes. What's more, the data in NEU directions are not always in good quality, and horizontal accuracy of the GPS station is higher than vertical accuracy. Sometimes, the data in vertical direction cannot be used, it is better not used the data in vertical direction. Sometimes, the accuracy of the data in vertical direction is lower than horizontal accuracy, it is better to take data weight into account in this case.

**Comment by jplckj** [comment]
Hi:

Actually, in Mudpy in you can assign different weights for horizon and vertical displacments  in “GF_list”. While the vertical component of GPS displacements are less accurate when comparing with horizontal component, they are actually not that bad, normally the sigma is about 1.5 to 2 times as horizontal’s, which provides valuable constraint on seismic source inversion. Besides, if there are collocated GPS and strong motion sensors, there is the possibility that vertical components could be as precise as horizontal ones.
