### ISSUE TITLE
 Stamps software

### ISSUE THREAD

**Issue by roseali21** [dmelgarm/MudPy#37]
I use the Envisat data for my case study and running the Stamps software. unfortunately, I have a error after running the step_coreg_simple script as following:

"ERROR   : [coregistration.cc[4058]]: code ???: No data found > threshold.
Caught error of EXCEPTION class!
It is: specific error
total cpu:     1    min 49.3288 sec"

**Comment by dmelgarm** [comment]
I think you might be on the wrong mailing list!

Diego.
