### ISSUE TITLE
[Errno 2] No such file or directory: 'pisco.mod.static.0.9000.sub0001.insar', problem during compute the GF

### ISSUE THREAD

**Issue by SiyuanZhao1** [dmelgarm/MudPy#49]
I am trying to inverse some InSAR data, after I downsampled the data to 1850 InSAR points, I use the "insartools.quadtree2mudpy" to prepare the .gflist file. However, during the Green function computation, at the step compute synthetics at stations for the source, an error called "No such file or directory: 'pisco.mod.static.0.9000.sub0001.insar' " happened. In the /GFs/statics, all the output files are empty. Could you help me with that, thanks very much.

<img width="699" alt="Screen Shot 2019-07-22 at 3 12 00 pm" src="https://user-images.githubusercontent.com/51397425/61607924-37093b80-ac94-11e9-8cd6-333ca3470171.png">

<img width="683" alt="Screen Shot 2019-07-22 at 3 19 01 pm" src="https://user-images.githubusercontent.com/51397425/61607957-48524800-ac94-11e9-8972-12bb5b2d7ad6.png">

[Insar.py.txt](https://github.com/dmelgarm/MudPy/files/3415805/Insar.py.txt)

[gflist.txt](https://github.com/dmelgarm/MudPy/files/3415807/gflist.txt)

**Comment by hidayatpanuntun** [comment]
Any solution for this error?
