### ISSUE TITLE
Inconsistent naming of static green's functions

### ISSUE THREAD

**Issue by seismicshaker** [dmelgarm/MudPy#63]
runslip.py copies staticgf in line 169 as
copy('staticgf',green_path+'static/'+model_name+'.static.'+strdepth+'.sub'+subfault)

green.py defines staticgf in line 286 as
green_file=model_name+".static."+strdepth+".sub"+subfault+'.gps'

**Comment by dmelgarm** [comment]
In the parallel version the naming is correct. In the near future I will deprecate the serial versions of the code. So should always run with ncpus>=2
