### ISSUE TITLE
Name of static green function files for gps incorrect

### ISSUE THREAD

**Issue by crowellbw** [dmelgarm/MudPy#64]
Line 286 is green.py

                    green_file=model_name+".static."+strdepth+".sub"+subfault+'.gps' #Output dir

should be

                    green_file=model_name+".static."+strdepth+".sub"+subfault #Output dir

**Comment by dmelgarm** [comment]
It is not. In the parallel version the naming is correct. In the near future I will deprecate the serial versions of the code. So should always run with ncpus>=2
