### ISSUE TITLE
error in example

### ISSUE THREAD

**Issue by susilosarimun** [dmelgarm/MudPy#65]
Dear All,

I try to run nepal inversion from examples folder by following the wiki.
But iget an error when running inversion, here my error:

--- RUNNING INVERSIONS ---

Running inversion 1 of 20 at regularization levels: ls =0.01 , lt = 0.0
Traceback (most recent call last):
  File "nepal_version2.inv.py", line 87, in <module>
    runslip.run_inversion(home,project_name,run_name,fault_name,model_name,GF_list,G_from_file,
  File "/usr/lib/python3/dist-packages/mudpy/runslip.py", line 714, in run_inversion
    VR,L2data=inv.get_VR(home,project_name,GF_list,sol,d,ds,decimate,WG,wd)
UnboundLocalError: local variable 'WG' referenced before assignment

"

Is there any solution for this error?

Thanks you very much 

Susilo

**Comment by zhanggh1978** [comment]
same as for me. not a clue for the problem. need help....many thanks

**Comment by zhanggh1978** [comment]
I found the solution:

Update nepal_version2.inv.py

The nepal_version2.inv.py does not properly run the inversion step if the weight = False. However, when I change weight = True it runs properly. The code is finding the weighted Green's function which is expressed as WG in the code. If the weight = False, WG is not generated. Hence, the software fails to produce the slip inversion.
