### ISSUE TITLE
Error running subduction.fq.py

### ISSUE THREAD

**Issue by Anupam2372** [dmelgarm/MudPy#66]
Dear All,

I try to run mudpy/examples/fakequakes/planar/subduction.fq.py for the case following the wiki.
**init=0
make_ruptures=1
make_GFs=0
make_synthetics=0
make_waveforms=0
load_distances=0
G_from_file=0**
Also I used python2.7 and python3.6 version but I get an error when running rupture, here my error:

... working on subfault 6970 of 7050
... working on subfault 6980 of 7050
... working on subfault 6990 of 7050
... working on subfault 7000 of 7050
... working on subfault 7010 of 7050
... working on subfault 7020 of 7050
... working on subfault 7030 of 7050
... working on subfault 7040 of 7050
Generating rupture scenarios
... Calculating ruptures for target magnitude Mw = 7.5
... ... working on rupture 0 of 5
Traceback (most recent call last):
  File "subduction.fq.py", line 102, in <module>
    shypo=center_subfault,use_hypo_fraction=use_hypo_fraction,shear_wave_fraction=shear_wave_fraction)
  File "/home/anupam/mudpy/src/python/mudpy/fakequakes.py", line 1206, in generate_ruptures
    no_random,shypo,use_hypo_fraction,shear_wave_fraction,max_slip_rule)
  File "/home/anupam/mudpy/src/python/mudpy/fakequakes.py", line 1356, in run_generate_ruptures
    C=vonKarman_correlation(Dstrike_selected,Ddip_selected,Ls,Ld,hurst)
  File "/home/anupam/mudpy/src/python/mudpy/fakequakes.py", line 384, in vonKarman_correlation
    r = sqrt((Dstrike/Lstrike)**2 + (Ddip/Ldip)**2)
TypeError: ufunc 'divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Is there any solution for this error?

Thank you very much
Anupam

**Comment by Cucoccc** [comment]
hello,I have the same question,Have you solved it,Could you sahre the solution with me?
